rest_api/urls.py
from django.conf.urls import url
from . import views

app_name = 'rest_api'


urlpatterns = [
	#url(r'^$', views.main, name='main'),
	url(r'login', views.rest_login, name='login'),
	url(r'logout', views.rest_logout, name='logout'),
	url(r'add_employee/',views.employee_list, name='employee_list'),
	url(r'todo_list/', views.todo_list, name='todo_list'),
	url(r'todo_detail/(?P<pk>\d+)',views.todo_detail, name='todo_detail'),
	url(r'org_list/', views.OrgList.as_view(), name='org_list'),
	url(r'org_detail/(?P<pk>\d+)',views.OrgDetail.as_view(), name='org_detail'),
	
]

todolist/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r"^", include('django.contrib.auth.urls')),
    url('admin/', admin.site.urls),
    url(r"^",include('rest_api.urls',namespace='rest_api')),
    url(r"^api/",include('rest_framework.urls', namespace='rest'))
]

rest_api/models.py
from django.db import models
from django.contrib.auth.models import User

class Organisation(models.Model):
	name = models.TextField(max_length=50,null=False, unique=True)

	def __str__(self):
		return self.name


class Employee(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE, related_name='employee')
	org = models.ForeignKey(Organisation, related_name='employees',on_delete=models.CASCADE)

	class Meta:
		unique_together = ('user', 'org')

	def __str__(self):
		return self.user.username


class ToDo(models.Model):
	title = models.TextField(max_length=100)
	text = models.TextField(max_length=2048, blank=True)
	org = models.ForeignKey(Organisation, related_name='todoList',on_delete=models.CASCADE)
	createdBy = models.ForeignKey(Employee,on_delete=models.CASCADE, related_name='todoList')

	def __str__(self):
		return self.title

rest_api/views.py
from django.shortcuts import render
from rest_framework import generics, status
from django.contrib.auth.decorators import *
from django.contrib.auth import authenticate, login, logout
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.shortcuts import redirect
from .models import *
from .serializers import *

'''def main(request):
	if request.user.is_authenticated and request.user.employee:
		employee = request.user.employee
	else:
		employee = None
	orgs = Organisation.objects.all()
	todo_list = employee.org.todoList.all()
	print(ToDoSerializer(todo_list, many=True).data)
	return render(request, 'rest_api/index.html',{'employee': EmployeeSerializer(employee).data, 
		'orgs': OrganisationSerializer(orgs, many=True).data,
		'todolist': ToDoSerializer(todo_list, many=True).data})'''

'''
{
	"org": 1,
	"email": "chingis@ch.bur",
	"password": "1211"
}
'''
def rest_login(request):
	email = request.POST['email']
	password = request.POST['password']
	org = request.POST['org']
	employee = Employee.objects.get(org=org,user__email=email)
	user = authenticate(username=employee.user.username, password=password)
	if user:
		login(request, user)
		return redirect("rest_api:main")
	else:
		return Response(status=status.HTTP_400_BAD_REQUEST)

def rest_logout(request):
	logout(request)
	return redirect("rest_api:main")


@api_view(['PUT','GET'])
def employee_list(request):
	if request.method == 'GET':
		print(request.user)
		if request.user.is_authenticated:
			employee_list = Employee.objects.filter(user__email=request.user.email)
			return Response(EmployeeSerializer(employee_list, many=True).data)
		else:
			return Response(status=status.HTTP_401_UNAUTHORIZED)
	if request.method == 'PUT':
		try:
			org_id = request.data.get('org')
			org = Organisation.objects.get(pk=org_id)
		except Exception as exc:
			print(str(exc))
			return Response(status=status.HTTP_404_NOT_FOUND)
		request.data['username'] = "{}_{}".format(request.data['email'],org.name)
		userSr = UserSerializer(data=request.data)
		if userSr.is_valid():
			user = userSr.save()
			empl = Employee.objects.create(org=org, user=user)
			return Response(EmployeeSerializer(empl).data, status=status.HTTP_201_CREATED)
		else:
			return Response(userSr.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET','PUT'])
def todo_list(request):
	print(request.data)
	try:
		employee = request.user.employee
		org = employee.org
	except Exception as exc:
		print(str(exc))
		return Response(status=status.HTTP_404_NOT_FOUND)
	if request.method == 'GET':
		print('get')
		todoList = org.todoList.all()
		return Response(ToDoSerializer(todoList,many=True).data)
	elif request.method == 'PUT':
		data = {key: item[0] for (key,item) in request.data if type(item) == 'list'}
		data.update({'createdBy':employee.pk, 'org': org.pk})
		print(data)
		print(type(data['title']))
		todo = ToDoSerializer(data=data)
		if todo.is_valid():
			todo.save()
			return Response(todo.data, status=status.HTTP_201_CREATED)
		else:
			print(todo.errors)
			return Response(todo.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET','PATCH','DELETE'])
def todo_detail(request,pk):
	try:
		todo = ToDo.objects.get(pk=pk)
	except Exception as exc:
		print(str(exc))
		return Response(status=status.HTTP_404_NOT_FOUND)

	if request.method == 'GET':
		return Response(ToDoSerializer(todo).data)
	elif request.method == 'PATCH':
		serializer = ToDoSerializer(instance=todo,data=request.data, partial=True)
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data, status=status.HTTP_201_CREATED)
		else:
			print(serializer.errors)
			return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
	elif request.method == 'DELETE':
		todo.delete()
		return Response(status=status.HTTP_204_NO_CONTENT)


class OrgList(generics.ListCreateAPIView):
    queryset = Organisation.objects.all()
    serializer_class = OrganisationSerializer

class OrgDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Organisation.objects.all()
    serializer_class = OrganisationSerializer

rest_api/templates/rest_api/index.html
<html>
<head>
<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
<style>
	.todo {
		border: 1px solid blue;
		border-radius: 3px;
	}
	.todo-list {
		display: flexbox;
	}
	.todo-title {
		font-weight: bold;
	}
	.save-btn {
		color: lightgreen;
		border: 1px solid green;
	}
	.delete-btn {
		color: red;
		border: 1px solid darkred;
	}
</style>
</head>
<body>
	<div class="navbar">
	{% if employee %}
		<span>Current user: {{employee.user.email}}</span>
		<span>Organisation: {{employee.org.name}}</span>
		<a href="{% url 'rest_api:logout' %}">Выйти</a>
	{% else %}
	<form action="{% url 'rest_api:login' %}" method="POST">
		<input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}" />
		<input type="text" name="email">
		<input type="password" name="password">
		<select name="org">
			{% for org in orgs %}<option value="{{org.id}}">{{org.name}}</option>{%endfor%}
		</select>
		<button type=submit >Войти</a>
	</form>
	{%endif %}
	</div>
	<section class="container">
		<h3>To do:</h6>
		<form action="{% url 'rest_api:todo_list' %}" method="PUT" id="create_todo">
			<input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}" />
			<input type="text" name="title" placeholder="title"><br>
			<textarea name="text" id="" cols="30" rows="10"></textarea>
			<button type="submit">Send</button>
		</form>
		<div class="todo_list">
			{%for todo in todolist %}
			<div class="todo">
				<span class="todo-title">{{todo.title}}</span><input type="text" value="{{ todo.text }}" />
				<span class="save-btn">Сохранить</span><span data-pk="{{todo.id}}" class="delete-btn">Удалить</span>
			</div>
			{% endfor %}
		</div>
	</section>
	<script>
	$(document).ready(function() {
		$("#create_todo").on('submit', create_todo)
	});
	function create_todo(e) {
		e.preventDefault();
		let data = $(e.target).serializeArray();
		let url = e.target.getAttribute('action');
		let method = e.target.getAttribute('method');
		let csrf = $(e.target).find('[name=csrfmiddlewaretoken]').val();
		$.ajax({url: url, headers: {'X-CSRFToken': csrf}, data: data, method: method, success: add_todo, error: (data)=>(console.log(data.responseText))});
	}
	function add_todo(data) {
		console.log(data);
		let template = `
		<div class="todo">
				<span class="todo-title">{{todo.title}}</span><input type="text" value="{{ todo.text }}" />
				<span class="save-btn">Сохранить</span><span data-pk="{{todo.id}}" class="delete-btn">Удалить</span>
			</div>
		`.replace('{{todo.title}}',data.title)
		.replace('{{ todo.text }}', data.text)
		.replace('{{todo.id}}', data.id);
	}
	</script>
</body>
</html>

rest_api/templates/rest_api/registration.html
<html>
<head>
	.wrapper {
	display: flexbox;
	}
</head>
<body>
	<form action="{% url'add_employee' %}">
		<label for="">Usename:<input type="text" name='username'></label>
		<label for="">Email:<input type="email" name='email'></label>
		<label for="">password:<input type="password" name='password'></label>
		<label for="">organisation:
			<select name="org">
				{% for org in orgs %}<option value="{{org.pk}}">{{org.name}}</option>{%endfor%}
			</select>
		</label>
		<button type="submit">Send</button>
	</form>
</body>
</html>